name: edbfly build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:23.3.1

    steps:
    - uses: actions/checkout@v1

    - name: Generate edbfly escript
      run: make release

    - name: Check edbfly version
      run: |
        _build/default/bin/edbfly version | sed -e 's/Version: //' > version.txt
        cat version.txt

    - name: Store edbfly as artifact
      if: endsWith(github.ref, 'refs/heads/master')
      uses: actions/upload-artifact@v2
      with:
        name: edbfly
        path: _build/default/bin/edbfly

    - name: Store version.txt as artifact
      if: endsWith(github.ref, 'refs/heads/master')
      uses: actions/upload-artifact@v2
      with:
        name: edbfly-version
        path: version.txt

  tag:
    needs: build

    runs-on: ubuntu-latest

    if: endsWith(github.ref, 'refs/heads/master')

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Download version.txt
      uses: actions/download-artifact@v2
      with:
        name: edbfly-version

    - name: Download edbfly
      uses: actions/download-artifact@v2
      with:
        name: edbfly

    - name: Push Tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token

      run: |
        go get -u github.com/tcnksm/ghr
        VERSION=$(cat version.txt)
        REPO=edbfly
        OWNER=drvspw
        $HOME/go/bin/ghr \
            -t ${GITHUB_TOKEN} \
            -u ${OWNER} \
            -r ${REPO} \
            -c ${GITHUB_SHA} \
            -delete \
            ${VERSION} ./edbfly

    - name: Delete artifacts
      uses: geekyeggo/delete-artifact@v1
      with:
        name: |
          edbfly
          edbfly-version
